_.ambient.rootmodule("object/")
    .include("object")
    .include("helper")
    .include("oophelper")
    .include("modeldefiner")
//    .include("property")
//    .include("method")
    .include("testobject", "debugmode")
