_.ambient.rootmodule("widget/")
    .require("sourcery/core/system/client/")
    .include("widgethelper")
    .include("widget")
    .include("gadget")
    .include("widgetscreen")
    .include("widgetwindow")
