_.ambient.rootmodule("dom/")
    .require("sourcery/core/globals/ui/")
//    .include("domevent")
    .include("htmlelement")
    .include("htmlbody")
    .include("htmldocument")
    .include("htmlevent")
    .include("htmleventhandler")
