_.ambient.rootmodule("basiclist/")
    .include("map")
    .include("linkedlistnode")
    .include("linkedlistroot")
//    .include("stacklist")
//    .include("listcursor")
//    .include("listsegment")

    .include("test.linkedlistroot", "debugmode")
//    .include("test.stacklist", "debugmode")
