_.ambient.rootmodule("skiplist/")
//    .include("skiplistcursor")
    .require("sourcery/core/algo/basiclist/")
    .include("skiplistnode")
    .include("skiplistroot")
    .include("skiplistsegment")
    .include("test.skiplistroot", "debugmode")
