_.ambient.rootmodule("skiplist/")
//    .include("skiplistcursor")
    .require("sourcery/core/algo/basiclist/")
    .include("skiplistnode")
    .include("skiplist")
    .include("skiplistsegment")
    .include("test.skiplist", "debugmode")
